Add Continous Delivery to DO

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,6 +37,12 @@ jobs:
         run: docker-compose up -d --build
       - name: Run Tests
         run: docker-compose exec -T web python -m pytest .
+      - name: Check for tag
+        run: |
+          if [[ -z "$GITHUB_REF_NAME" ]]; then
+            echo "Tag missing for current commit!"
+            exit 1
+          fi
 
   build:
     name: Build and Push Images
@@ -48,14 +54,14 @@ jobs:
         uses: actions/checkout@v2
       - name: Build images
         run: |
-          docker build -t ${{ secrets.DOCKERHUB_NAMESPACE }}/${{env.WEB_IMAGE}}:latest -f ./project/Dockerfile ./project
-          docker build -t ${{ secrets.DOCKERHUB_NAMESPACE }}/${{env.DB_IMAGE}}:latest -f ./project/db/Dockerfile ./project/db
+          docker build -t ${{ secrets.DOCKERHUB_NAMESPACE }}/$WEB_IMAGE:$GITHUB_REF_NAME -f ./project/Dockerfile ./project
+          docker build -t ${{ secrets.DOCKERHUB_NAMESPACE }}/$DB_IMAGE:$GITHUB_REF_NAME -f ./project/db/Dockerfile ./project/db
       - name: Log in to Dockerhub
         run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_NAMESPACE }} --password-stdin
       - name: Push to Dockerhub
         run: |
-          docker push ${{ secrets.DOCKERHUB_NAMESPACE }}/${{env.WEB_IMAGE}}:latest
-          docker push ${{ secrets.DOCKERHUB_NAMESPACE }}/${{env.DB_IMAGE}}:latest 
+          docker push ${{ secrets.DOCKERHUB_NAMESPACE }}/$WEB_IMAGE:$GITHUB_REF_NAME
+          docker push ${{ secrets.DOCKERHUB_NAMESPACE }}/$DB_IMAGE:$GITHUB_REF_NAME 
 
 
   deploy:
@@ -74,28 +80,16 @@ jobs:
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null
           ssh-keyscan ${{ secrets.SERVER_IPV4 }} >> ~/.ssh/known_hosts
           ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
-          ssh root@${{ secrets.SERVER_IPV4 }} whoami 
-          scp ./docker-compose-swarm.yml root@${{ secrets.SERVER_IPV4 }}
 
-      
-      
-      
-      # - name: copy file via ssh key
-      #   uses: appleboy/scp-action@master
-      #   with:
-      #     host: ${{ secrets.HOST }}
-      #     username: ${{ secrets.USERNAME }}
-      #     port: ${{ secrets.PORT }}
-      #     key: ${{ secrets.KEY }}
-      #     source: "tests/a.txt,tests/b.txt"
-      #     target: "test"
-      # - name: executing remote ssh commands using ssh key
-      #   uses: appleboy/ssh-action@master
-      #   with:
-      #     host: ${{ secrets.HOST }}
-      #     username: ${{ secrets.USERNAME }}
-      #     key: ${{ secrets.KEY }}
-      #     port: ${{ secrets.PORT }}
-      #     script: |
-      #       whoami
-      #       whoami
+          echo PAPERTRAIL_URL=$PAPERTRAIL_URL >> .env
+          echo WEB_IMAGE=${{ secrets.DOCKERHUB_NAMESPACE }}/$WEB_IMAGE:$GITHUB_REF_NAME >> .env
+          echo DB_IMAGE=${{ secrets.DOCKERHUB_NAMESPACE }}/$DB_IMAGE:$GITHUB_REF_NAME >> .env
+
+          scp ./.env ./docker-compose-swarm.yml root@${{ secrets.SERVER_IPV4 }}:~
+          ssh root@${{ secrets.SERVER_IPV4 }} << 'ENDSSH'
+            source .env
+            echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_NAMESPACE }} --password-stdin
+            docker pull $WEB_IMAGE
+            docker pull $DB_IMAGE
+            docker stack deploy --compose-file=docker-compose-swarm.yml optideploy
+          ENDSSH
